import Navbar from "@/src/Navbar";
import Head from "next/head";
import ImageModal from "./imagemodal";
import Image from "next/image";
import Hero from "../public/img/hero.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>fire of love</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col text-clr2 font-avenirbook">
        <Navbar />
        <div className="flex text-clr2 min-h-screen bg-clr4 pt-36 px-4 lg:px-28">
          <div className="flex flex-col text-2xl text-left font-semibold w-3/5 align-middle content-center justify-center pr-24">
            <div className="lg:flex justify-between">
              <h1 className="text-3xl lg:text-6xl lg:leading-12 lg:pb-0 pb-8">
                Que tal{" "}
                <span className="font-acc italic font-thin">
                  planejar o futuro
                </span>{" "}
                do seu negócio imobiliário hoje?
              </h1>
            </div>
            <div className="bg-clr2 h-0.5 rounded-md mb-2 mt-10" />
            <div className="flex">
            <p className="text-xl font-avenirbook mt-6 leading-10">
                A Torodan apresenta as melhores soluções para a inclusão do seu
                negócio imobiliário no mercado digital. Através de engenharias
                de marketing modernas e uma ampla cobertura em diversas
                plataformas, garantimos uma presença online segura e voltada
                para resultados reais. Traga suas vendas para a web de maneira
                inteligente e fácil.
              </p>
            </div>
          </div>
          <div className="relative w-2/5">
            <Image src={Hero} alt="hero" className="object-cover"></Image>
          </div>
        </div>

        <ImageModal />
      </main>
    </>
  );
}
